sonar.projectKey=vg-ms-attendance
sonar.projectName=vg-ms-attendance
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.coveragePlugin=jacoco
sonar.exclusions=**/dto/**,**/config/AttendanceSchemaInitializer.java
