server:
  port: ${PORT:8085}

spring:
  application:
    name: vg-ms-task

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
      max-life-time: 60m
      validation-query: SELECT 1

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

services:
  academic-url: ${ACADEMIC_SERVICE_URL:http://localhost:8082}
  student-url: ${STUDENT_SERVICE_URL:http://localhost:8083}

logging:
  level:
    org.springframework.r2dbc: INFO
    com.vg.task: DEBUG
